server:
  port: 9000

spring:
  application:
    name: dubbo-spring-boot-starter
  dubbo:
    server: true
    registry: N/A
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: anywhere

spring.jpa.properties.hibernate.hbm2ddl.auto: create-drop
