spring:
  application:
    name: dubbo-spring-boot-starter
  dubbo:
    server: true
    registry: N/A
  datasource:
    url: jdbc:mysql://localhost:3306/promotion
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
